- name: Install APT Dependencies
  apt: name="{{item}}" update_cache=yes cache_valid_time=86400
  with_items:
    - git
    - vim
    - python
    - python-dev
    - python-pip
    - build-essential
    - ntp

- name: Fetch the git repo
  git:
    clone: yes
    force: yes
    repo: "{{ git_repo_url }}"
    dest: "{{ git_dest_dir }}"
    version: "{{ git_version }}"

- name: Upgrade pip/virtualenv
  pip:
    name: "{{ item.name }}"
    extra_args: "-U"
  with_items:
    - name: "pip"
    - name: "virtualenv"

- name: Destroy the virtualenv
  file:
    path: "{{ git_dest_dir }}/.venv"
    state: absent

- name: Install the python package
  pip:
    name: "{{ git_dest_dir }}"
    virtualenv: "{{ git_dest_dir }}/.venv"
    editable: False
    extra_args: "-U"

- name: Create Config File
  template:
    src: psn-notifier-config.j2
    dest: /etc/psn-notifier-config

- name: Create Startup Script
  template:
    src: psn-notifier.service.j2
    dest: /etc/systemd/system/psn-notifier.service

- name: Start the service
  systemd:
    state: restarted
    daemon_reload: yes
    name: psn-notifier
